checks:
    php: true
    javascript: true

build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: scss-lint-run
                        use_website_config: true
